#check default firewall------|
#                       if firewalld -|        
#     |             |---------|       |
#     V      (False)|                 |
#                   |                 |
#             Install firewalld       |(True)
#                   |                 |
# OK _______________V_________________|
#                       
# 
 
- name: "stop ufw"
  service:
    name: ufw
    state: stopped

- name: "delete ufw -> install firewald"
  apt:
    name: ufw
    state: absent
  apt:
    name: firewalld
    state: present

- name: "config firewall"
  service:
    name: firewalld
    state: started


