---

- name: "Install Elasticsearch"
  apt:
    name: elasticsearch
    update_cache: yes 
  tags:
    - elastic

- name: "Start elasticsearch"  
  service: 
    name: elasticsearch
    state: started
  tags:
    - elastic
