
- name: "install dependencies for nginx"
  apt:
    name: ["python3-apt","wget","git","build-essential","libpcre3","libpcre3-dev",
          "libssl-dev","libtool","autoconf","apache2-dev","libxml2-dev","libcurl4-openssl-dev","automake","pkgconf","zlib1g-dev","liblua5.1-0-dev"]
    state: present

- name: "unarchive"  
  unarchive:
    src: "https://www.openssl.org/source/openssl-1.1.1c.tar.gz"     
    dest: /usr/src/
    remote_src: yes
    validate_certs: false

- name: "Shell openssl"
  shell: "./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib"
  args:
    chdir: /usr/src/openssl-1.1.1c/

- name: "Make openssl"
  make:
    chdir: /usr/src/openssl-1.1.1c/
  make:
    chdir: /usr/src/openssl-1.1.1c/
    target: test
  make:
    chdir: /usr/src/openssl-1.1.1c/
    target: install

- name: "Config openssl"
  shell: echo "/usr/local/ssl/lib" > /etc/ld.so.conf.d/
  shell: ldconfig -v 
  shell: echo "PATH=\"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/ssl/bin\"" > /etc/environment
  args:
    executable: /bin/bash
  shell: source /etc/environment

- name: "Openssl"
  shell:  openssl version
  register: opens

- name: "Check installed"
  debug: 
    msg: "Openssl is installed"
  when: opens.stdout.find("1.1.1c") != -1
