- name: "Download modsecurity"
  git:
    repo: 'https://github.com/SpiderLabs/ModSecurity.git'
    dest: /usr/src/ModSecurity
    version: nginx_refactoring
    update: no
 
- name: "Install modsecurity"
  shell: ./autogen.sh \
   ./configure \
   --enable-standalone-module
  args:
    chdir: /usr/src/ModSecurity/

- name: "Modsecurity OWASP rules download"
  git:
    repo: "https://github.com/SpiderLabs/owasp-modsecurity-crs.git"
    dest: /etc/nginx/owasp-modsecurity-crs
    update: no

- name: "ModSecurity setup"  
  shell: cp src-setup.conf.example src-setup.conf
  args:
    chdir: /etc/nginx/owasp-modsecurity-crs
  shell: cp REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf 
  args:
    chdir: /etc/nginx/owasp-modsecurity-crs/rules
  shell: cp RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
  args:
    chdir: /etc/nginx/owasp-modsecurity-crs/rules

