---

- name: "Install elk"
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - include_vars: ../vars/install-variables.yml 
    - import_tasks: ansible-install-dep.yml
  
- name: "Config elastic"
  hosts: elastic-server
  gather_facts: yes
  become: yes
  tasks:
    - include_vars: ../vars/elastic-cfg.yml
    - import_tasks: ansible-elastic.yml
  
    - name: "Config elastic javammachine"
      template:
        src: ../templates/elastic-jvm.options.yml.j2
        dest: "/etc/elasticsearch/jvm.options"
 
    - name: "Config elastic"
      template:
        src: ../templates/elasticsearch.yml.j2
        dest: "/etc/elasticsearch/elasticsearch.yml"
  tags:
    - elastic


- name: "Config kibana"
  hosts: elastic-server
  gather_facts: yes
  become: yes
  tasks:
    - include_vars: ../vars/kibana-cfg.yml
    - import_tasks: ansible-kibana.yml
  
    - name: "Config kibana"
      template:
        src: ../templates/kibana.yml.j2
        dest: "/etc/kibana/kibana.yml"
  tags:
    - kibana

- name: "Config logstash with beats"
  hosts: logstash-server
  gather_facts: yes
  become: yes
  tasks:
    - include_vars: ../vars/logstash-cfg.yml
    - include_vars: ../vars/elastic-cfg.yml
    - import_tasks: ansible-logstash.yml
    
    - name: "Config logstash javammachine"
      template:
        src: ../templates/logst-jvm.options.yml.j2
        dest: "/etc/logstash/jvm.options"
    
    - name: "Config logstash pipeline"
      template:
        src: ../templates/logstash-pipelines.yml.j2
        dest: "/etc/logstash/pipelines.yml"
    
        ### This is useless now
        #    - name: "Config logstash.yml"
        #template:
        #src: ../templates/logstash.yml.j2
        #dest: "/etc/logstash/config/"
    
    - name: "logstash plugins configs"
      template: 
        src: ../templates/logstash-conf/10-input.conf.j2
        dest: "/etc/logstash/conf.d/10-input.conf"
    - name: "logstash plugins configs"
      template: 
        src: ../templates/logstash-conf/20-filter.conf.j2
        dest: "/etc/logstash/conf.d/20-filter.conf"
    - name: "logstash plugins configs"
      template: 
        src: ../templates/logstash-conf/30-output.conf.j2
        dest: "/etc/logstash/conf.d/30-output.conf"
    
    - include_vars: ../vars/filebeat-cfg.yml

    - import_tasks: ansible-filebeats.yml
      tags:
        - filebeats
        - all_beats
    - name: "Copy default settings"
      template:
        src: ../templates/beats-conf/filebeat.yml.j2
        dest: "etc/filebeat/filebeat.yml"
      tags:
        - filebeats
        - all_beats
  tags:
    - logstash

- name: "Firewall setup"
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - include_vars: ../vars/elastic-cfg.yml
    - include_vars: ../vars/kibana-cfg.yml
    - include_vars: ../vars/logstash-cfg.yml
    - package_facts:
        manager: auto
    - import_tasks: ansible-firewalld-install.yml
      when: " 'firewalld' not in ansible_facts.packages "
    - import_tasks: ansible-firewalld-config.yml
  tags:
    - config-firewall
        
